# ==================================================
# APPLICATION
# ==================================================
server.port=8080
spring.application.name=investor-portfolio-hexagonal

# ==================================================
# EUREKA
# ==================================================
eureka.client.enabled=false

# ==================================================
# URLS
# ==================================================
custom.server.url=https://api.advisorkhoj.com/portfolio
hostDomainUrl=https://api.advisorkhoj.com/portfolio

vendor.logo.url=https://api.advisorkhoj.com/images/vendors/
amc.logo.url=https://api.advisorkhoj.com/nse/images/amc-logo/
custom.logo.url = https://api.themfbox.com/
# ==================================================
# STATIC FILES
# ==================================================
spring.web.resources.static-locations=file:/usr/local/tomcat/temp/

pdfDir=/usr/local/tomcat/temp/download/pdf/
pdfUrl=/download/pdf/

fontDir=/usr/local/tomcat/temp/fonts/
logoDir=/usr/local/tomcat/temp/images/clients/
chartDir=/usr/local/tomcat/temp/images/chart/

thymeleafDir=/usr/local/tomcat/temp/thymeleaf/

# IMPORTANT
thymeleafCss=/thymeleaf/css/bootstrap-pdf.css
thymeleafCustomCss=/thymeleaf/css/custom.css

# ==================================================
# PRIMARY DATASOURCE
# ==================================================
spring.datasource.primary.jdbc-url=jdbc:mysql://169.38.132.168:3306/mfportfolio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.primary.username=user_mf_dev
spring.datasource.primary.password=Mfbox@96860!$
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.primary.hikari.pool-name=PrimaryHikariPool
spring.datasource.primary.hikari.maximum-pool-size=100
spring.datasource.primary.hikari.minimum-idle=10
spring.datasource.primary.hikari.connection-timeout=30000

# ==================================================
# SECONDARY DATASOURCE
# ==================================================
spring.datasource.secondary.jdbc-url=jdbc:mysql://169.38.132.168:3306/advisorkhoj_amfi?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.secondary.username=dev_amfi_microservice
spring.datasource.secondary.password=Amfi@96860!$
spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.secondary.hikari.pool-name=SecondaryHikariPool
spring.datasource.secondary.hikari.maximum-pool-size=100
spring.datasource.secondary.hikari.minimum-idle=10
spring.datasource.secondary.hikari.connection-timeout=60000

# ==================================================
# JPA
# ==================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ==================================================
# JWT
# ==================================================
jwt.secret-key=OoZT8hVO0IOr7WZuU7beibI4wQ5cByYX!

# ==================================================
# COMPRESSION
# ==================================================
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html
server.compression.min-response-size=1024

# ==================================================
# SWAGGER
# ==================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs

# ==================================================
# LOGGING
# ==================================================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN
logging.level.com.netflix.discovery=WARN

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

# ==================================================
# DEVTOOLS
# ==================================================
spring.devtools.restart.enabled=false
spring.devtools.add-properties=false

amfi.service.base-url=https://api.advisorkhoj.com/amfi